version: "3"
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - "2181:2181"
  ##########################################################################################
  #      Kafka                                                                             #
  ##########################################################################################
  kafka_1:
    container_name: kafka_1
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9092:9092"
      - "1091:1091"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: "114.118.13.40"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "fshd_nginx_access_log:3:3" # 主题:分区:备份
      JMX_PORT: 1091
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/kafka/kafka1:/kafka
      - ./conf/kafka/log4j.properties:/opt/kafka/config/log4j.properties
    depends_on:
      - zookeeper
  kafka_2:
    container_name: kafka_2
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9093:9092"
      - "1092:1092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: "114.118.13.40"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      JMX_PORT: 1092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/kafka/kafka2:/kafka
      - ./conf/kafka/log4j.properties:/opt/kafka/config/log4j.properties
    depends_on:
      - zookeeper
  kafka_3:
    container_name: kafka_3
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9094:9092"
      - "1093:1093"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: "114.118.13.40"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      JMX_PORT: 1093
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/kafka/kafka3:/kafka
      - ./conf/kafka/log4j.properties:/opt/kafka/config/log4j.properties
    depends_on:
      - zookeeper
  kafka-manager:
    container_name: kafka-manager
    image: sheepkiller/kafka-manager
    restart: always
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "letmein"
      KAFKA_MANAGER_AUTH_ENABLED: "true"
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    ports:
      - "9000:9000"
    expose:
      - "9000"
    links:
      - zookeeper
      - kafka_1
      - kafka_2
      - kafka_3

